export { Navbar } from './Navbar'
export { Hero } from './Hero'
export { About } from './About'
export { Projects } from './Projects'
export { Skills } from './Skills'
export { Contact } from './Contact'
export { Footer } from './Footer'
